apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    workload: metrics
    prometheus: prometheus-service
    role: alert-rules
  name: prometheus-k8s-custom-alerting-rules
  namespace: prometheus
spec:
  groups:
  - name: custom statistic
    rules:
    - alert: Memory percentage is >95%
      annotations:
        description: "Node memory utilization is > 95%"
        message: "Out of memory (instance {{ $labels.node }})"
      expr: label_replace(sum(kube_metrics_server_nodes_mem) by (exported_instance), "node", "$1", "exported_instance", "(.*)") / on(node) ((sum(kube_node_status_allocatable_memory_bytes) by (node)) / 1024) * 100 > 95
      for: 10m
      labels:
        severity: P3
        resource: '{{ $labels.node }}'