apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secretvaultsync
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          # Set to true for using managed identity
    userAssignedIdentityID: 1800fda2-de0e-48ae-b2ce-5fb2d57129ad   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: tripinsightvault2        # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: SQL-DBNAME
          objectType: secret              # object types: secret, key, or cert
          objectAlias: SQL_DBNAME
        - |
          objectName: SQL-PASSWORD
          objectType: secret
          objectAlias: SQL_PASSWORD
        - |
          objectName: SQL-SERVER
          objectType: secret
          objectAlias: SQL_SERVER
        - |
          objectName: SQL-USER
          objectType: secret
          objectAlias: SQL_USER
    tenantId: 052140be-e22a-4512-93d7-886f703e0497                # The tenant ID of the key vault
