apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-java
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryiax7978.azurecr.io/tripinsights/user-java:1.0
        volumeMounts:
          - mountPath: /secrets
            name: secrets
            readOnly: true
        ports:
        - containerPort: 80
      volumes:
      - name: secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secretvaultsync
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-java
  name: user-java-service
  namespace: api
spec:
  selector:
    app: user-java
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
