apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  labels:
    app: poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryiax7978.azurecr.io/tripinsights/poi:1.0
        volumeMounts:
          - mountPath: /secrets
            name: secrets
            readOnly: true
        ports:
        - containerPort: 80
      volumes:
      - name: secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secretvaultsync
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: poi
    workload: metrics
  name: poi-service
  namespace: api
spec:
  selector:
    app: poi
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
