apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  labels:
    app: userprofile
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryiax7978.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: tripsecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: userprofile
  name: userprofile-service
spec:
  selector:
    app: userprofile
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
