apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  labels:
    app: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryiax7978.azurecr.io/tripinsights/trips:1.0
        volumeMounts:
          - mountPath: /secrets
            name: secrets
            readOnly: true
        ports:
        - containerPort: 80
      volumes:
      - name: secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secretvaultsync
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trips
    workload: metrics
  name: trips-service
  namespace: api
spec:
  selector:
    app: trips
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80

