apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: service-scraper-api-web
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
    interval: 60s
  jobLabel: service-scraper-api-web
  namespaceSelector:
    matchNames:
    - api
    - web
    - insurance
  selector:
    matchLabels:
      workload: metrics
