apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tripsinsights-web-ingress
  namespace: web
spec:
  ingressClassName: nginx
  rules:
#  - host: openhack.northeurope.cloudapp.azure.com
  - http:
     paths:   
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tripviewer-service
            port:
              number: 80